name: CI

on:
  push:
    branches:
      - 'master'
  release:
    types:
      - created
  pull_request:

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: Run lint
        run: |
          npm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: Run Tests
        run: |
          npm run coverage

  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: Launch build
        run: |
          npm run build

      - name: Archive package artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            /home/runner/work/terra-front/terra-front/dist

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit

      - name: Launch build
        run: |
          npm run build-storybook -- --quiet

      - name: Archive storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook-static
          path: |
            /home/runner/work/terra-front/terra-front/storybook-static/

  deploy-storybook:
    name: Deploy StoryBook
    runs-on: ubuntu-latest
    needs: [lint, tests, build-storybook]
    steps:
      - uses: actions/checkout@v3

      - name: Download storybook artifacts
        uses: actions/download-artifact@v2
        with:
          name: storybook-static

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install netlify cli
        run: |
          npm i -g netlify-cli

      - name: Deploy storybook
        run:
          npx netlify deploy
            --site=${{ secrets.NETLIFY_SITE_ID }}
            --auth=${{ secrets.NETLIFY_ACCESS_TOKEN }}
            --dir=./storybook-static
            --message "${{ github.sha }} ${{ github.ref_name }}"
            --prod

  deploy-npm:
    name: Deploy package to NPM registry
    runs-on: ubuntu-latest
    needs: [lint, tests, build-package]
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
