name: CI

on:
  push:
    branches:
      - '*' # TODO: master
  release:
    types:
      - created
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --cache ~/.npm --prefer-offline --no-audit

      - name: Run lint
        run: |
          npm run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --cache ~/.npm --prefer-offline --no-audit

      - name: Run Tests
        run: |
          npm run coverage

  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --cache ~/.npm --prefer-offline --no-audit

      - name: Launch build
        run: |
          npm run build
      - name: Archive package artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            /home/runner/work/terra-front/dist

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    container: node:12.8
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci
      - name: Launch build
        run: |
          npm run build-storybook -- --quiet
      - name: Archive storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            /home/runner/work/terra-front/storybook-static/